-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 21, 2024 lúc 02:29 PM
-- Phiên bản máy phục vụ: 10.4.32-MariaDB
-- Phiên bản PHP: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `lavender`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `categories`
--

CREATE TABLE `categories` (
  `id` int(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `day_Create` date DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `categories`
--

INSERT INTO `categories` (`id`, `name`, `day_Create`, `status`) VALUES
(1, 'index_product\r\n', '2024-11-21', 'còn'),
(2, 'newarrials', '2024-11-21', 'còn'),
(3, 'bestselling', '2024-11-21', 'còn'),
(4, 'tops', '2024-11-21', 'còn'),
(5, 'bottoms', '2024-11-21', 'còn');

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `orders`
--

CREATE TABLE `orders` (
  `id` int(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(100) NOT NULL,
  `address` varchar(100) DEFAULT NULL,
  `purchase_date` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `price` int(100) NOT NULL,
  `payment_method` varchar(100) DEFAULT NULL,
  `payment_status` varchar(100) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `users_id` int(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `orders_details`
--

CREATE TABLE `orders_details` (
  `id` int(100) NOT NULL,
  `product_id` int(100) NOT NULL,
  `price` int(100) NOT NULL,
  `quantity` int(100) NOT NULL,
  `order_id` int(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `products`
--

CREATE TABLE `products` (
  `id` int(100) NOT NULL,
  `image_01` varchar(100) DEFAULT NULL,
  `image_02` varchar(100) DEFAULT NULL,
  `image_03` varchar(100) DEFAULT NULL,
  `image_04` varchar(100) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `price` int(100) DEFAULT NULL,
  `oldprice` int(100) DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `quantity` int(100) DEFAULT NULL,
  `day_create` date DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `categories_id` int(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `products`
--

INSERT INTO `products` (`id`, `image_01`, `image_02`, `image_03`, `image_04`, `name`, `price`, `oldprice`, `description`, `quantity`, `day_create`, `status`, `categories_id`) VALUES
(1, 'sp1.webp', 'sp1_2.webp', 'sp1_3.webp', 'sp1_4.webp', '2BAR BABY TEE - BLUE', 199000, 286000, '| SWE® | 2BAR BABY TEE <br>\r\nCOLOR: BLUE <br>\r\nMATERIAL: COTTON 100% <br>\r\nSIZE: XS <br>\r\n<br>\r\n\r\n2BAR BABY TEE - Mẫu áo BABY TEE mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động. Điểm nhấn của áo nằm ở họa tiết logo SWE mới được thêu tinh tế giữa ngực áo kèm các đường line chạy dọc 2 bên sườn tạo cảm giác nổi bật và ấn tượng hơn cho áo. <br> <br>\r\n\r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 4 chiều, định lượng 250gsm, thiết kế form BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam.\r\nSize XS: Chiều cao dưới 1m70, cân nặng dưới 60kg\r\n<br> <br>\r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo.<br>\r\nNOW AVAILABLE ONLINE & IN - STORE', 50, '2024-11-21', 'còn hàng', 1),
(2, 'sp2.jpg', 'sp2_2.webp', 'sp2_3.webp', 'sp2_4.webp', '2BAR BABY TEE - RED', 199000, 286000, '| SWE® | 2BAR BABY TEE <br>\r\nCOLOR: RED <br>\r\nMATERIAL: COTTON 100% <br>\r\nSIZE: XS <br>\r\n<br>\r\n\r\n2BAR BABY TEE - Mẫu áo BABY TEE mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động. Điểm nhấn của áo nằm ở họa tiết logo SWE mới được thêu tinh tế giữa ngực áo kèm các đường line chạy dọc 2 bên sườn tạo cảm giác nổi bật và ấn tượng hơn cho áo. <br> <br>\r\n\r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 4 chiều, định lượng 250gsm, thiết kế form BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam.\r\nSize XS: Chiều cao dưới 1m70, cân nặng dưới 60kg\r\n<br> <br>\r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo.<br>\r\nNOW AVAILABLE ONLINE & IN - STORE', 50, NULL, 'còn hàng', 1),
(3, 'sp3.jpg', 'sp3_2.webp', 'sp3_3.webp', 'sp3_4.webp', '2BAR SHORTS - BLUE\r\n', 245000, 352000, '| SWE® | 2BAR SHORTS<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M<br> \r\n<br> \r\n2BAR SHORTS - Chiếc quần shorts mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động.<br> \r\n<br> \r\nĐiểm nhấn của quần nằm ở họa tiết logo SWE mới được thêu tinh tế phía bên đùi trái kèm các đường line chạy dọc 2 bên tạo cảm giác nổi bật và ấn tượng hơn cho quần.<br> \r\n<br> \r\nPhần thắt lưng tô điểm bằng những chi tiết viền vải được may đều xung quanh eo. Với thiết kế thể thao cùng chất liệu thoải mái, đây sẽ là một sự lựa chọn hoàn hảo dành cho những bạn nữ ưa thích vận động.<br> \r\n<br> \r\nQuần shorts SWE được sử dụng vải nỉ chân cua cotton, định lượng 440gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 65kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', 20, NULL, 'còn', 1),
(4, 'sp4.webp', 'sp4_2.jpg', 'sp4_3.webp', 'sp4_4.webp', '2BAR SHORTS - RED', 245000, 352000, '| SWE® | 2BAR SHORTS<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M<br> \r\n<br> \r\n2BAR SHORTS - Chiếc quần shorts mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động.<br> \r\n<br> \r\nĐiểm nhấn của quần nằm ở họa tiết logo SWE mới được thêu tinh tế phía bên đùi trái kèm các đường line chạy dọc 2 bên tạo cảm giác nổi bật và ấn tượng hơn cho quần.<br> \r\n<br> \r\nPhần thắt lưng tô điểm bằng những chi tiết viền vải được may đều xung quanh eo. Với thiết kế thể thao cùng chất liệu thoải mái, đây sẽ là một sự lựa chọn hoàn hảo dành cho những bạn nữ ưa thích vận động.<br> \r\n<br> \r\nQuần shorts SWE được sử dụng vải nỉ chân cua cotton, định lượng 440gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 65kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '0000-00-00', 'còn hàng', 1),
(5, 'sp5.webp', 'sp5_2.jpg', 'sp5_3.jpg', 'sp5_4.webp', '24 TEE - RED', 245000, 462000, '| SWE® | 24 TEE<br> \r\nCOLOR: RED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M<br> \r\n<br> \r\n24 TEE - Chiếc áo thun mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động.<br> \r\n<br> \r\nĐiểm nhấn của áo nằm ở họa tiết logo SWE mới được thêu tinh tế phía trước ngực kèm các chi tiết tinh giản tạo cảm giác nổi bật và ấn tượng hơn cho sản phẩm.<br> \r\n<br> \r\nVới thiết kế thoải mái cùng chất liệu cotton mềm mịn, đây sẽ là một sự lựa chọn hoàn hảo dành cho những bạn trẻ yêu thích phong cách casual.<br> \r\n<br> \r\nForm áo được Fit size theo tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 65kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(6, 'sp6.webp', 'sp6_2.webp', 'sp6_3.webp', 'sp6_4.webp', 'EYE TEE - BLACK', 275000, 305000, '| SWE® | EYE TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nEYE TEE - Chiếc áo thun mới trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE được thiết kế với phong cách hiện đại và cá tính.<br> \r\n<br> \r\nĐiểm nhấn của áo là họa tiết độc đáo hình \"EYE\" được in chất lượng cao ở mặt trước, mang lại sự nổi bật và phong cách thời thượng.<br> \r\n<br> \r\nVới chất liệu cotton cao cấp, áo không chỉ thoáng mát mà còn mang lại sự thoải mái tối ưu trong các hoạt động thường ngày.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn của người Việt Nam, bạn nên cân nhắc chọn size lớn hơn nếu đang phân vân giữa hai size.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 75kg<br> \r\nSize L: Chiều cao từ 1m75 trở lên, cân nặng từ 65kg - 85kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(7, 'sp7.webp', 'sp7_2.webp', 'sp7_3.webp', 'sp7_4.webp', 'HAPPY TEE - BLACK', 275000, 363000, '| SWE® | HAPPY TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nHAPPY TEE - Chiếc áo thun mới trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang đến phong cách trẻ trung và tươi vui.<br> \r\n<br> \r\nĐiểm nhấn của áo là họa tiết \"HAPPY\" độc đáo ở mặt trước, thể hiện sự năng động và tích cực.<br> \r\n<br> \r\nVới chất liệu cotton mềm mại và bền đẹp, áo mang lại cảm giác thoải mái tối ưu cho người mặc.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 75kg<br> \r\nSize L: Chiều cao từ 1m75 trở lên, cân nặng từ 65kg - 85kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '0000-00-00', 'còn hàng', 3),
(8, 'sp8.webp', 'sp8_2.webp', 'sp8_3.webp', 'sp8_4.webp', 'HEARTS TEE - BLACK', 275000, 305000, '| SWE® | HEARTS TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nHEARTS TEE - Chiếc áo thun mới trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách ngọt ngào và cá tính.<br> \r\n<br> \r\nĐiểm nhấn của áo là họa tiết \"HEARTS\" độc đáo ở mặt trước, mang lại nét nổi bật đầy thu hút.<br> \r\n<br> \r\nVới chất liệu cotton chất lượng cao, áo không chỉ thoải mái mà còn phù hợp cho nhiều hoạt động khác nhau.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 75kg<br> \r\nSize L: Chiều cao từ 1m75 trở lên, cân nặng từ 65kg - 85kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br> \r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form áo<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(9, 'sp9.webp', 'sp9_2.webp', 'sp9_3.webp', 'sp9_4.webp', 'ILY TEE - CREAM', 275000, 462000, '| SWE® | ILY TEE<br> \r\nCOLOR: CREAM<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nILY TEE - Một thiết kế mang phong cách nhẹ nhàng và tinh tế, nằm trong bộ sưu tập \"FOR THE YOUTH\".<br> \r\n<br> \r\nHọa tiết \"ILY\" được in trước ngực mang đến thông điệp yêu thương và kết nối.<br> \r\n<br> \r\nChất liệu cotton mềm mịn cùng form dáng thoải mái, thích hợp cho các hoạt động hàng ngày.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nSize S: Chiều cao dưới 1m65, cân nặng từ 40kg - 65kg<br> \r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng từ 55kg - 75kg<br> \r\nSize L: Chiều cao từ 1m75 trở lên, cân nặng từ 65kg - 85kg<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(10, 'sp10.webp', 'sp10_2.webp', 'sp10_3.webp', 'sp10_4.webp', 'KID TEE - WHITE', 250000, 462000, '| SWE® | KID TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nKID TEE - Một thiết kế dễ thương dành cho các bạn trẻ năng động và yêu thích sự tối giản.<br> \r\n<br> \r\nHọa tiết đơn giản nhưng đầy cá tính tạo nên sự trẻ trung và năng động.<br> \r\n<br> \r\nVới chất liệu cotton thoáng mát, đây là một lựa chọn lý tưởng cho các bạn yêu thích sự thoải mái.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(11, 'sp11.webp', 'sp11_2.webp', 'sp11_3.webp', 'sp11_4.webp', 'SIGNATURE TEE - PINK', 285000, 418000, '| SWE® | SIGNATURE TEE<br> \r\nCOLOR: PINK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nSIGNATURE TEE - Thiết kế đặc trưng của nhà SWE, mang phong cách thanh lịch và hiện đại.<br> \r\n<br> \r\nĐiểm nhấn của áo là logo \"SIGNATURE\" được in nổi bật trước ngực, tạo sự khác biệt đầy tinh tế.<br> \r\n<br> \r\nChất liệu cotton cao cấp đảm bảo sự mềm mại và bền đẹp.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(12, 'sp12.webp', 'sp12_2.webp', 'sp12_3.webp', 'sp12_4.webp', 'SWEVN TEE - BLACK', 295000, 305000, '| SWE® | SWEVN TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nSWEVN TEE - Một sản phẩm đặc biệt mang phong cách mạnh mẽ và cá tính, đại diện cho thương hiệu SWE.<br> \r\n<br> \r\nHọa tiết \"SWEVN\" được thiết kế nổi bật trước ngực, thể hiện sự tự tin và cá tính.<br> \r\n<br> \r\nChất liệu cotton cao cấp mang lại cảm giác thoải mái và bền bỉ.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 3),
(13, 'sp13.webp', 'sp13_2.webp', 'sp13_3.jpg', 'sp13_4.webp', 'HOLLOW TEE - WHITE', 400000, 440000, '| SWE® | SWEVN TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nSWEVN TEE - Một sản phẩm đặc biệt mang phong cách mạnh mẽ và cá tính, đại diện cho thương hiệu SWE.<br> \r\n<br> \r\nHọa tiết \"SWEVN\" được thiết kế nổi bật trước ngực, thể hiện sự tự tin và cá tính.<br> \r\n<br> \r\nChất liệu cotton cao cấp mang lại cảm giác thoải mái và bền bỉ.<br> \r\n<br> \r\nForm áo chuẩn Fit size theo tiêu chuẩn người Việt Nam. Nếu bạn đang phân vân giữa hai size, hãy chọn size lớn hơn.<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '0000-00-00', 'còn hàng', 2),
(14, 'sp14.jpg', 'sp14_2.jpg', 'sp14_3.jpg', 'sp14_4.jpg', 'EDGE WASHED JEANS - BLUE', 650000, 715000, '| SWE® | EDGE WASHED JEANS<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nEDGE WASHED JEANS - Chiếc quần jeans mới nằm trong bộ sưu tập \"Refined Origins\" được thiết kế theo phong cách đơn giản với điểm nhấn nằm ở những chi tiết cách điệu 2 bên thân quần và đường viền túi sau bắt mắt. Quần được xử lý washed để tạo ra những tone màu bụi bặm.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form quần suông nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '0000-00-00', 'còn hàng', 2),
(15, 'sp15.jpg', 'sp15_2.jpg', 'sp15_3.jpg', 'sp15_4.jpg', 'EDGE WASHED JEANS - LIGHT BLUE', 650000, 715000, '| SWE® | EDGE WASHED JEANS<br> \r\nCOLOR: LIGHT BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nEDGE WASHED JEANS - Chiếc quần jeans mới nằm trong bộ sưu tập \"Refined Origins\" được thiết kế theo phong cách đơn giản với điểm nhấn nằm ở những chi tiết cách điệu 2 bên thân quần và đường viền túi sau bắt mắt. Quần được xử lý washed để tạo ra những tone màu bụi bặm.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form quần suông nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(16, 'sp16.webp', 'sp16_2.webp', 'sp16_3.jpg', 'sp16_4.jpg', 'EDGE WASHED JEANS - BLACK', 650000, 715000, '| SWE® | EDGE WASHED JEANS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nEDGE WASHED JEANS - Chiếc quần jeans mới nằm trong bộ sưu tập \"Refined Origins\" được thiết kế theo phong cách đơn giản với điểm nhấn nằm ở những chi tiết cách điệu 2 bên thân quần và đường viền túi sau bắt mắt. Quần được xử lý washed để tạo ra những tone màu bụi bặm.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form quần suông nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(17, 'sp17.jpg', 'sp17_2.jpg', 'sp17_3.jpg', 'sp17_4.jpg', 'DUNE DESTROYED JEANS - BLUE', 690000, 759000, '| SWE® | DUNE DESTROYED JEANS<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L<br> \r\n<br> \r\nDUNE DESTROYED JEANS - Chiếc quần jeans mới nằm trong bộ sưu tập \"Refined Origins\" được thiết kế theo phong cách bụi bặm với điểm nhấn nằm ở những chi tiết sờn rách 2 bên ống quần và túi sau rất bắt mắt. Quần được xử lý washed để tạo ra tone màu ấn tượng. Phần lai quần được xả lai tạo cảm giác cá tính hơn cho trang phục của bạn.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form quần suông nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(18, 'sp18.webp', 'sp18_2.jpg', 'sp18_3.jpg', 'sp18_4.jpg', 'HAZE WASHED BABY TEE - BLUE', 280000, 305000, '| SWE® | HAZE WASHED BABY TEE<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHAZE WASHED BABY TEE - Mẫu áo thun mới nằm trong bộ sưu tập \"Refined Origins\" có form dáng BABY TEE, thiết kế basic cùng với màu sắc được sử dụng công nghệ wash ấn tượng. Điểm nhấn của chiếc áo nằm ở các đường may phối rã rất thời trang kèm với họa tiết logo SWE mới được thêu tinh tế ở giữa ngực.<br> \r\n<br> \r\nÁo SWE BABY TEE được sử dụng vải thun gân COTTON 100%, định lượng 330gsm, thiết kế form BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE..<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(19, 'sp19.webp', 'sp19_2.jpg', 'sp19_3.jpg', 'sp19_4.jpg', 'HAZE WASHED BABY TEE - GRAPHITE', 280000, 305000, '| SWE® | HAZE WASHED BABY TEE<br> \r\nCOLOR: GRAPHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHAZE WASHED BABY TEE - Mẫu áo thun mới nằm trong bộ sưu tập \"Refined Origins\" có form dáng BABY TEE, thiết kế basic cùng với màu sắc được sử dụng công nghệ wash ấn tượng. Điểm nhấn của chiếc áo nằm ở các đường may phối rã rất thời trang kèm với họa tiết logo SWE mới được thêu tinh tế ở giữa ngực.<br> \r\n<br> \r\nÁo SWE BABY TEE được sử dụng vải thun gân COTTON 100%, định lượng 330gsm, thiết kế form BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE..<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(20, 'sp20.webp', 'sp20_2.jpg', 'sp20_3.jpg', 'sp20_4.jpg', 'CREW LS JERSEY - RED', 383000, 495000, 'CREW LS JERSEY - RED<br> \r\nCOLOR: RED<br> \r\nMATERIAL: POLYESTER 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nCREW LS JERSEY - Chiếc áo tay dài mới được thiết kế theo phong cách thể thao với điểm nhấn nằm ở họa tiết mặt trước, mặt sau và 2 bên tay áo được sử dụng chất liệu in kéo lụa sắc nét. Phần thân áo và tay áo được may phối viền nổi bật. Áo sử dụng vải mesh lưới tạo cảm giác thoải mái và thoáng mát hơn cho bạn khi vận động.<br> \r\n<br> \r\nÁo Jersey SWE vẫn được sử dụng POLYESTER 100%, định lượng 210gsm, thiết kế form áo LS JERSEY nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(21, 'sp21.webp', 'sp21_2.jpg', 'sp21_3.jpg', 'sp21_4.jpg', 'CREW LS JERSEY - BLACK', 383000, 495000, 'CREW LS JERSEY - RED<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: POLYESTER 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nCREW LS JERSEY - Chiếc áo tay dài mới được thiết kế theo phong cách thể thao với điểm nhấn nằm ở họa tiết mặt trước, mặt sau và 2 bên tay áo được sử dụng chất liệu in kéo lụa sắc nét. Phần thân áo và tay áo được may phối viền nổi bật. Áo sử dụng vải mesh lưới tạo cảm giác thoải mái và thoáng mát hơn cho bạn khi vận động.<br> \r\n<br> \r\nÁo Jersey SWE vẫn được sử dụng POLYESTER 100%, định lượng 210gsm, thiết kế form áo LS JERSEY nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(22, 'sp22.jpg', 'sp22_2.jpg', 'sp22_3.jpg', 'sp22_4.jpg', 'AIRY DENIM SHORTS - DARK BLUE', 500000, 550000, '| SWE® | AIRY DENIM SHORTS<br> \r\nCOLOR: DARK BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nAIRY DENIM SHORTS - Chiếc quần shorts mới được thiết kế đơn giản nhưng đầy cá tính với điểm nhấn nằm ở những đường may xếp ly rất thời trang. Quần sử dụng chất liệu acid wash tạo ra tone màu xanh đặc trưng của các sản phẩm denim. Phần túi sau được thêu logo SWE mới sắc nét.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form BAGGY SHORTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(23, 'sp23.jpg', 'sp23_2.jpg', 'sp23_3.jpg', 'sp23_4.jpg', 'NOMAD DENIM SHORTS - WASHED BLUE', 600000, 660000, '| SWE® | NOMAD DENIM SHORTS <br> \r\nCOLOR: WASHED BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nNOMAD DENIM SHORTS - Chiếc quần shorts mới được thiết kế theo phong cách cargo shorts với điểm nhấn nằm ở những chiếc túi hộp kèm các đường may phối rã rập đặt xung quanh quần rất bắt mắt. Quần sử dụng chất liệu acid wash để tạo ra tone màu xanh bụi bặm. Phần túi sau được thêu logo SWE mới sắc nét.<br> \r\n<br> \r\nQuần SWE được sử dụng vải denim cotton 100%, định lượng 13 Oz, thiết kế form BAGGY CARGO SHORTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(24, 'sp24.webp', 'sp24_2.jpg', 'sp24_3.webp', 'sp24_4.webp', 'DOODLE TEE - BEIGE', 340000, 440000, '| SWE® | DOODLE TEE<br> \r\nCOLOR: BEIGE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nDOODLE TEE - Chiếc áo thun mới với thiết kế Typography đơn giản. Điểm nhấn của áo nằm ở họa tiết chữ ở mặt trước và mặt sau được sử dụng chất liệu thêu móc xích sắc nét.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(25, 'sp25.webp', 'sp25_2.jpg', 'sp25_3.jpg', 'sp25_4.jpg', 'DOODLE TEE - PINK', 340000, 440000, '| SWE® | DOODLE TEE<br> \r\nCOLOR: PINK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nDOODLE TEE - Chiếc áo thun mới với thiết kế Typography đơn giản. Điểm nhấn của áo nằm ở họa tiết chữ ở mặt trước và mặt sau được sử dụng chất liệu thêu móc xích sắc nét.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(26, 'sp26.webp', 'sp26_2.jpg', 'sp26_3.webp', 'sp26_4.webp', 'DOODLE TEE - BLACK', 340000, 440000, '| SWE® | DOODLE TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nDOODLE TEE - Chiếc áo thun mới với thiết kế Typography đơn giản. Điểm nhấn của áo nằm ở họa tiết chữ ở mặt trước và mặt sau được sử dụng chất liệu thêu móc xích sắc nét.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(27, 'sp27.jpg', 'sp27_2.jpg', 'sp27_3.jpg', 'sp27_4.jpg', 'BADGE TEE - GRAPHITE', 323000, 418000, '| SWE® | BADGE TEE<br> \r\nCOLOR: GRAPHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBADGE TEE - Chiếc áo thun mới với thiết kế basic được sử dụng phương pháp wash để tạo ra những tone màu ấn tượng. Điểm nhấn của áo nằm ở họa tiết logo SWE mới làm bằng kim loại được đặt tinh tế phía bên ngực trái. Phần cổ áo, tay áo và lai áo có những chi tiết rách tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(28, 'sp28.jpg', 'sp28_2.jpg', 'sp28_3.jpg', 'sp28_4.jpg', 'BADGE TEE - RUSTIC', 323000, 418000, '| SWE® | BADGE TEE<br> \r\nCOLOR: RUSTIC<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBADGE TEE - Chiếc áo thun mới với thiết kế basic được sử dụng phương pháp wash để tạo ra những tone màu ấn tượng. Điểm nhấn của áo nằm ở họa tiết logo SWE mới làm bằng kim loại được đặt tinh tế phía bên ngực trái. Phần cổ áo, tay áo và lai áo có những chi tiết rách tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(29, 'sp29.webp', 'sp29_2.jpg', 'sp29_3.jpg', 'sp29_4.webp', 'LOUD TEE - BLACK', 323000, 418000, '| SWE® | LOUD TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nLOUD TEE - Chiếc áo thun mới với thiết kế đơn giản nhưng đầy cá tính. Điểm nhấn của áo nằm ở họa tiết chữ ở mặt trước kèm logo SWE mới phía sau lưng được sử dụng chất liệu in kéo lụa tạo hiệu ứng crack giả vintage sắc nét.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(30, 'sp30.webp', 'sp30_2.webp', 'sp30_3.webp', 'sp30_4.jpg', 'LOUD TEE - WHITE', 323000, 418000, '| SWE® | LOUD TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nLOUD TEE - Chiếc áo thun mới với thiết kế đơn giản nhưng đầy cá tính. Điểm nhấn của áo nằm ở họa tiết chữ ở mặt trước kèm logo SWE mới phía sau lưng được sử dụng chất liệu in kéo lụa tạo hiệu ứng crack giả vintage sắc nét.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(31, 'sp31.jpg', 'sp31_2.jpg', 'sp31_3.jpg', 'sp31_4.jpg', 'SLATE JEANS', 462000, 660000, '| SWE® | SLATE JEANS<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nSLATE JEANS - Chiếc quần mới nằm trong bộ SLATE SET được sử dụng chất liệu vải denim cotton 100%, độ dày 13 Oz. Với chi tiết đường rã phối 2 bên sườn quần kèm chi tiết đường chỉ may ở phần gối mang đến sự phá cách và tinh nghịch cho những ai yêu quyến rũ. Phần nút kim loại được đúc logo SWE sắc nét. Quần sử dụng công nghệ stone wash tạo ra tone màu xanh đặc trưng của các sản phẩm denim.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(32, 'sp32.jpg', 'sp32_2.jpg', 'sp32_3.jpg', 'sp32_4.jpg', 'SLATE JACKET', 554000, 792000, '| SWE® | SLATE JACKET<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nSLATE JACKET - Chiếc áo khoác mới nằm trong bộ SLATE SET được sử dụng chất liệu vải denim cotton 100%, độ dày 13 Oz. Áo được lấy cảm hứng từ những chiếc Vintage denim jacket, với chi tiết túi được cách điệu kèm chi tiết xếp ly đằng sau áo ấn tượng. Phần nút kim loại được đúc logo SWE sắc nét. Áo sử dụng công nghệ stone wash tạo ra tone màu xanh đặc trưng của các sản phẩm denim.<br> \r\n<br> \r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 2),
(33, 'sp33.webp', 'sp33_2.jpg', 'sp33_3.jpg', 'sp33_4.jpg', 'ROCKY TEE - FADED', 340000, 440000, '| SWE® | ROCKY TEE<br> \r\nCOLOR: FADED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nROCKY TEE - Chiếc áo thun mới với tông màu xám đen được wash ấn tượng. Điểm nhấn của áo nằm ở họa tiết hình in được sử dụng chất liệu in trame cực ngầu ở mặt trước. Phần cổ áo, tay áo và lai áo có những chi tiết rách tinh tế tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(34, 'sp34.webp', 'sp34_2.jpg', 'sp34_3.jpg', 'sp34_4.webp', 'IX JERSEY TEE - BLACK', 340000, 440000, '| SWE® | IX JERSEY TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nIX JERSEY TEE - Chiếc áo thun mới với thiết kế theo phong cách thể thao và năng động. Điểm nhấn của áo nằm ở những họa tiết hình in kéo lụa tạo hiệu ứng vintage đầy cá tính. Phần tay áo được may phối viền nổi bật kèm cổ áo V neck mang đến sự trẻ trung và thoải mái khi sử dụng.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(35, 'sp35.webp', 'sp35_2.jpg', 'sp35_3.jpg', 'sp35_4.jpg', 'IX JERSEY TEE - WHITE', 340000, 440000, '| SWE® | IX JERSEY TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nIX JERSEY TEE - Chiếc áo thun mới với thiết kế theo phong cách thể thao và năng động. Điểm nhấn của áo nằm ở những họa tiết hình in kéo lụa tạo hiệu ứng vintage đầy cá tính. Phần tay áo được may phối viền nổi bật kèm cổ áo V neck mang đến sự trẻ trung và thoải mái khi sử dụng.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(36, 'sp36.webp', 'sp36_2.jpg', 'sp36_3.webp', 'sp36_4.webp', 'CRIMSON SHIRT - BLACK', 336000, 528000, '| SWE® | CRIMSON SHIRT<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: 95% POLYESTER - 5% SPANDEX<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nCRIMSON SHIRT - Chiếc áo sơ mi mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE. Áo được thiết kế phong cách tối giản với điểm nhấn nằm ở họa tiết logo SWE mới được thêu tinh tế bên ngực phải kèm một chiếc nút đỏ được đính trên túi áo phía bên ngực trái.<br> \r\n<br> \r\nÁo sơ mi SWE được sử dụng vải kaki thun, định lượng 160gsm, nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(37, 'sp37.webp', 'sp37_2.jpg', 'sp37_3.webp', 'sp37_4.webp', 'CRIMSON SHIRT - WHITE', 336000, 528000, '| SWE® | CRIMSON SHIRT<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: 95% POLYESTER - 5% SPANDEX<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nCRIMSON SHIRT - Chiếc áo sơ mi mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE. Áo được thiết kế phong cách tối giản với điểm nhấn nằm ở họa tiết logo SWE mới được thêu tinh tế bên ngực phải kèm một chiếc nút đỏ được đính trên túi áo phía bên ngực trái.<br> \r\n<br> \r\nÁo sơ mi SWE được sử dụng vải kaki thun, định lượng 160gsm, nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(38, 'sp38.webp', 'sp38_2.jpg', 'sp38_3.jpg', 'sp38_4.jpg', 'HOOK TEE - RED', 285000, 418000, '| SWE® | HOOK TEE<br> \r\nCOLOR: RED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHOOK TEE - Chiếc áo thun với artwork được thiết kế theo phong cách thể thao nhưng rất cá tính. Điểm nhấn của áo nằm ở các họa tiết mặt trước và sau được sử dụng chất liệu in kéo lụa sắc nét, font chữ ấn tượng cùng với phối màu tương phản tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(39, 'sp39.webp', 'sp39_2.webp', 'sp39_3.jpg', 'sp39_4.jpg', 'HOOK TEE - WHITE', 285000, 418000, '| SWE® | HOOK TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHOOK TEE - Chiếc áo thun với artwork được thiết kế theo phong cách thể thao nhưng rất cá tính. Điểm nhấn của áo nằm ở các họa tiết mặt trước và sau được sử dụng chất liệu in kéo lụa sắc nét, font chữ ấn tượng cùng với phối màu tương phản tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(40, 'sp40.webp', 'sp40_2.jpg', 'sp40_3.jpg', 'sp40_4.jpg', 'HOOK TEE - BLACK', 285000, 418000, '| SWE® | HOOK TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHOOK TEE - Chiếc áo thun với artwork được thiết kế theo phong cách thể thao nhưng rất cá tính. Điểm nhấn của áo nằm ở các họa tiết mặt trước và sau được sử dụng chất liệu in kéo lụa sắc nét, font chữ ấn tượng cùng với phối màu tương phản tạo cảm giác nổi bật hơn cho trang phục của bạn.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(41, 'sp41.jpg', 'sp41_2.jpg', 'sp41_3.jpg', 'sp41_4.jpg', 'VEST TEE - FADED', 285000, 440000, '| SWE® | VEST TEE<br> \r\nCOLOR: FADED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nVEST TEE - Chiếc áo thun mới với thiết kế basic và sử dụng phương pháp wash để tạo ra tone màu xám đậm ấn tượng. Điểm nhấn của áo nằm ở họa tiết logo SWE mới được thêu tinh tế giữa ngực áo kèm theo những đường may phối rã rập tạo cảm giác nổi bật hơn cho áo.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4);
INSERT INTO `products` (`id`, `image_01`, `image_02`, `image_03`, `image_04`, `name`, `price`, `oldprice`, `description`, `quantity`, `day_create`, `status`, `categories_id`) VALUES
(42, 'sp42.jpg', 'sp42_2.jpg', 'sp42_3.jpg', 'sp42_4.jpg', 'VEST TEE - ASH', 285000, 440000, '| SWE® | VEST TEE<br> \r\nCOLOR: ASH<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nVEST TEE - Chiếc áo thun mới với thiết kế basic và sử dụng phương pháp wash để tạo ra tone màu xám đậm ấn tượng. Điểm nhấn của áo nằm ở họa tiết logo SWE mới được thêu tinh tế giữa ngực áo kèm theo những đường may phối rã rập tạo cảm giác nổi bật hơn cho áo.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(43, 'sp43.webp', 'sp43_2.webp', 'sp43_3.webp', 'sp43_4.webp', 'INTERWAVE TEE - RED', 312000, 429000, '| SWE® | INTERWAVE TEE<br> \r\nCOLOR: RED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nINTERWAVE TEE - Chiếc áo thun mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động. Áo được lấy cảm hứng từ mẫu áo WAVELINES TEE cũ kèm thêm các họa tiết mới của bộ sưu tập được in kéo lụa sắc nét. Điểm nhấn của áo nằm ở các đường line lượn sóng dọc 2 bên cánh tay.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(44, 'sp44.webp', 'sp44_2.webp', 'sp44_3.webp', 'sp44_4.webp', 'INTERWAVE TEE - BLUE', 312000, 429000, '| SWE® | INTERWAVE TEE<br> \r\nCOLOR: BLUE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nINTERWAVE TEE - Chiếc áo thun mới nằm trong bộ sưu tập \"FOR THE YOUTH\" của nhà SWE mang phong cách trẻ trung và năng động. Áo được lấy cảm hứng từ mẫu áo WAVELINES TEE cũ kèm thêm các họa tiết mới của bộ sưu tập được in kéo lụa sắc nét. Điểm nhấn của áo nằm ở các đường line lượn sóng dọc 2 bên cánh tay.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(45, 'sp45.jpg', 'sp45_2.jpg', 'sp45_3.jpg', 'sp45_4.jpg', 'NINER TEE - BLACK', 312000, 429000, '| SWE® | NINER TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nNINER TEE - Chiếc áo thun mới với artwork được thiết kế theo phong cách thể thao và rất cá tính. Điểm nhấn của áo nằm ở các họa tiết mặt trước và sau được sử dụng chất liệu in trame kéo lụa giả vintage sắc nét, font chữ ấn tượng cùng với màu sắc tương phản tạo cho hình in nổi bật hơn trên bề mặt áo màu đen.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(46, 'sp46.webp', 'sp46_2.webp', 'sp46_3.webp', 'sp46_4.webp', 'NINER TEE - CREAM', 312000, 429000, '| SWE® | NINER TEE<br> \r\nCOLOR: CREAM<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nNINER TEE - Chiếc áo thun mới với artwork được thiết kế theo phong cách thể thao và rất cá tính. Điểm nhấn của áo nằm ở các họa tiết mặt trước và sau được sử dụng chất liệu in trame kéo lụa giả vintage sắc nét, font chữ ấn tượng cùng với màu sắc tương phản tạo cho hình in nổi bật hơn trên bề mặt áo màu đen.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(47, 'sp47.webp', 'sp47_2.jpg', 'sp47_3.jpg', 'sp47_4.jpg', 'YOUTH LS TEE - CREAM', 336000, 528000, '| SWE® | YOUTH LS TEE<br> \r\nCOLOR: CREAM<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nYOUTH LS TEE - Chiếc áo thun tay dài mới với thiết kế theo phong cách racing cực ngầu. Điểm nhấn của áo nằm ở các họa tiết mặt trước, mặt sau và 2 tay áo được in trame sắc nét. Chiếc áo phù hợp dành cho các bạn nam có cá tính mạnh hoặc các bạn nữ muốn tìm kiếm gu thời trang mới cho bản thân.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(48, 'sp48.jpg', 'sp48_2.jpg', 'sp48_3.webp', 'sp48_4.jpg', 'HONEY TEE - BLACK', 209000, 440000, '| SWE® | HONEY TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nHONEY TEE - Chiếc áo thun mới với điểm nhấn nằm ở họa tiết chữ \"NO MONEY NO HONEY\" được đính hạt cườm DMC trên nền vải đen tạo cảm giác nổi bật hơn cho áo.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 2 chiều, định lượng 250gsm, thiết kế form SWE regular nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(49, 'sp49.webp', 'sp49_2.jpg', 'sp49_3.webp', 'sp49_4.webp', 'KA TANK TOP - WHITE (MEN)', 90000, 197000, '| SWE® | KA TANK TOP<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nKA TANK TOP - Mẫu áo tank top mới với thiết kế đơn giản được may form fit với body. Điểm nhấn của áo nằm ở họa tiết KID ATELIER được thêu bằng chỉ màu đen trên nền áo trắng phía trước ngực áo tạo cảm giác nổi bật nhưng vẫn không kém phần tinh tế.<br> \r\n<br> \r\nÁo tank top SWE được sử dụng vải thun bo gân COTTON 100%, định lượng 200gsm, thiết kế form SLIM FIT nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(50, 'sp50.webp', 'sp50_2.webp', 'sp50_3.webp', 'sp50_4.webp', 'KA TANK TOP - WHITE (WOMEN)', 90000, 197000, '| SWE® | KA TANK TOP<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nKA TANK TOP - Mẫu áo tank top mới với thiết kế đơn giản được may form fit với body. Điểm nhấn của áo nằm ở họa tiết KID ATELIER được thêu bằng chỉ màu đen trên nền áo trắng phía trước ngực áo tạo cảm giác nổi bật nhưng vẫn không kém phần tinh tế.<br> \r\n<br> \r\nÁo tank top SWE được sử dụng vải thun bo gân COTTON 100%, định lượng 200gsm, thiết kế form SLIM FIT nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(51, 'sp51.jpg', 'sp51_2.webp', 'sp51_3.jpg', 'sp51_4.jpg', 'INFINITY BABY TEE - BLACK', 149000, 297000, '| SWE® | INFINITY BABY TEE<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nINFINITY BABY TEE - Mẫu áo thun BABY TEE mới với thiết kế form raglan. Điểm nhấn của áo nằm ở họa tiết logo BEYOND THE STAR được thêu phía trước ngực áo tinh tế kèm các đường may phối rã rập chạy xung quanh tạo cảm giác nổi bật và ấn tượng hơn cho áo.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 4 chiều, định lượng 240gsm, thiết kế form raglan BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(52, 'sp52.webp', 'sp52_2.webp', 'sp52_3.webp', 'sp52_4.webp', 'INFINITY BABY TEE - WHITE', 149000, 297000, '| SWE® | INFINITY BABY TEE<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nINFINITY BABY TEE - Mẫu áo thun BABY TEE mới với thiết kế form raglan. Điểm nhấn của áo nằm ở họa tiết logo BEYOND THE STAR được thêu phía trước ngực áo tinh tế kèm các đường may phối rã rập chạy xung quanh tạo cảm giác nổi bật và ấn tượng hơn cho áo.<br> \r\n<br> \r\nÁo thun SWE vẫn được sử dụng COTTON 100% thuần tự nhiên 4 chiều, định lượng 240gsm, thiết kế form raglan BABY TEE nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm áo được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 4),
(53, 'sp53.webp', 'sp53_2.webp', 'sp53_3.webp', 'sp53_4.webp', 'NEBULA CARGO PANTS - WHITE', 408000, 528000, '| SWE® | NEBULA CARGO PANTS<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: NYLON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nNEBULA CARGO PANTS - Chiếc quần cargo được thiết kế theo phong cách hiphop. Với điểm nhấn nằm ở phần túi hộp được phối dây ấn tượng kèm phần ống quần được phối lưới độc đáo. Quần có sử dụng dây rút ở eo và ống quần giúp bạn dễ dàng tăng chỉnh kích cỡ để phù hợp với cơ thể.<br> \r\n<br> \r\nQuần SWE được sử dụng vải nylon 100%, thiết kế form CARGO PANTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(54, 'sp54.webp', 'sp54_2.jpg', 'sp54_3.jpg', 'sp54_4.jpg', 'NEBULA CARGO PANTS - BLACK', 408000, 528000, '| SWE® | NEBULA CARGO PANTS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: NYLON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nNEBULA CARGO PANTS - Chiếc quần cargo được thiết kế theo phong cách hiphop. Với điểm nhấn nằm ở phần túi hộp được phối dây ấn tượng kèm phần ống quần được phối lưới độc đáo. Quần có sử dụng dây rút ở eo và ống quần giúp bạn dễ dàng tăng chỉnh kích cỡ để phù hợp với cơ thể.<br> \r\n<br> \r\nQuần SWE được sử dụng vải nylon 100%, thiết kế form CARGO PANTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> \r\n<br>\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(55, 'sp55.webp', 'sp55_2.jpg', 'sp55_3.jpg', 'sp55_4.jpg', 'BLISS JEANS - BLACK', 610000, 792000, '| SWE® | BLISS JEANS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBLISS JEANS - Được sử dụng chất liệu vải denim đen chân xám, trọng lượng 11,5 Oz. Với phương pháp xử lý wash tạo màu, tạo xước theo sớ vải kèm tiêm dơ nhẹ và phun PP theo vị trí giúp quần có được tone màu độc đáo. Điểm nhấn của quần nằm ở những chi tiết cách điệu chạy dọc xung quanh ống. Mang đến sự phá cách và tinh nghịch cho những ai yêu quyến rũ.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(56, 'sp56.jpg', 'sp56_2.jpg', 'sp56_3.jpg', 'sp56_4.jpg', 'CHOPPED DENIM SHORTS - WASHED', 520000, 572000, '| SWE® | CHOPPED DENIM SHORTS<br> \r\nCOLOR: WASHED<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nCHOPPED DENIM SHORTS - Được sử dụng chất liệu vải jeans đen chân xám, trọng lượng 11,5 Oz. Với phương pháp xử lý wash tạo màu, tạo xước theo sớ vải kèm tiêm dơ nhẹ và phun PP theo vị trí giúp quần có được tone màu độc đáo. Phần túi quần phía trước và sau được thiết kế đặc biệt để bạn có thể dễ dàng đựng được nhiều vật dụng khi ra đường. Form dáng BAGGY tạo sự rộng rãi, thoải mái khi sử dụng.<br> \r\n<br> \r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(57, 'sp57.jpg', 'sp57_2.jpg', 'sp57_3.jpg', 'sp57_4.jpg', 'LOOSE SWEATPANTS - GRAY', 400000, 572000, '| SWE® | LOOSE SWEATPANTS<br> \r\nCOLOR: GRAY<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nLOOSE SWEATPANTS - Chiếc quần mới nằm trong set nỉ LOOSE. Điểm nhấn của quần nằm ở họa tiết logo SWE và logo BEYOND THE STAR được thêu tệp màu tinh tế ở phía trước kèm với tone màu xám được phối đặc biệt.<br> \r\n<br> \r\nQuần SWE được sử dụng vải nỉ chân cua, định lượng 400gsm, thiết kế form SWEATPANTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(58, 'sp58.jpg', 'sp58_2.jpg', 'sp58_3.jpg', 'sp58_4.jpg', 'LOOSE SWEATPANTS - WASHED', 400000, 572000, '| SWE® | LOOSE SWEATPANTS<br> \r\nCOLOR: WASHED<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nLOOSE SWEATPANTS - Chiếc quần mới nằm trong set nỉ LOOSE. Điểm nhấn của quần nằm ở họa tiết logo SWE và logo BEYOND THE STAR được thêu tệp màu tinh tế ở phía trước kèm với tone màu xám được phối đặc biệt.<br> \r\n<br> \r\nQuần SWE được sử dụng vải nỉ chân cua, định lượng 400gsm, thiết kế form SWEATPANTS nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(59, 'sp59.webp', 'sp59_2.webp', 'sp59_3.jpg', 'sp59_4.jpg', 'KA STRIPED TROUSERS\r\n', 330000, 660000, '| SWE® | KA STRIPED TROUSERS<br> \r\nCOLOR: STRIPED BLUE<br> \r\nMATERIAL: DENIM COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nKA STRIPED TROUSERS - Chiếc quần đang trở thành Hot trend với điểm nhấn nằm ở họa tiết sọc trắng xanh được dệt sắc nét. Bên cạnh đó là dòng chữ KID ATELIER thêu 3D bằng chỉ trắng ở túi sau. Ngoài ra, quần còn được sử dụng dây rút để điều chỉnh kích thước vòng eo cùng form dáng BAGGY vừa mang đến sự thoải mái khi sử dụng, vừa tạo sự phá cách và độc đáo cho sản phẩm.<br> \r\n<br> \r\nQuần SWE được sử dụng chất liệu vải denim cotton 100%, định lượng 11 Oz nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(60, 'sp60.jpg', 'sp60_2.jpg', 'sp60_3.jpg', 'sp60_4.jpg', 'BOXER SHORTS - STRIPED PINK', 84000, 132000, '| SWE® | BOXER SHORTS<br> \r\nCOLOR: STRIPED PINK<br> \r\nMATERIAL: KATEFORD FABRIC<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBOXER SHORTS - Những chiếc quần Boxer đang dần trở thành xu hướng ở thời điểm hiện tại bởi sự thoáng mát và thoái mái của chúng. Với họa tiết kẻ sọc trendy kèm đai thun được dệt logo thương hiệu SWE sẽ giúp bạn dễ dàng tô điểm thêm cho bộ outfit của mình ấn tượng và nhiều màu sắc hơn.<br> \r\n<br> \r\nQuần Boxer SWE được sử dụng vải Oxford, định lượng 170gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(61, 'sp61.jpg', 'sp61_2.webp', 'sp61_3.webp', 'sp61_4.webp', 'BOXER SHORTS - STRIPED BLUE', 84000, 132000, '| SWE® | BOXER SHORTS<br> \r\nCOLOR: STRIPED BLUE<br> \r\nMATERIAL: KATEFORD FABRIC<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBOXER SHORTS - Những chiếc quần Boxer đang dần trở thành xu hướng ở thời điểm hiện tại bởi sự thoáng mát và thoái mái của chúng. Với họa tiết kẻ sọc trendy kèm đai thun được dệt logo thương hiệu SWE sẽ giúp bạn dễ dàng tô điểm thêm cho bộ outfit của mình ấn tượng và nhiều màu sắc hơn.<br> \r\n<br> \r\nQuần Boxer SWE được sử dụng vải Oxford, định lượng 170gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(62, 'sp62.jpg', 'sp62_2.webp', 'sp62_3.webp', 'sp62_4.jpg', 'BOXER SHORTS - STRIPED BLACK', 84000, 132000, '| SWE® | BOXER SHORTS<br> \r\nCOLOR: STRIPED BLACK<br> \r\nMATERIAL: KATEFORD FABRIC<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nBOXER SHORTS - Những chiếc quần Boxer đang dần trở thành xu hướng ở thời điểm hiện tại bởi sự thoáng mát và thoái mái của chúng. Với họa tiết kẻ sọc trendy kèm đai thun được dệt logo thương hiệu SWE sẽ giúp bạn dễ dàng tô điểm thêm cho bộ outfit của mình ấn tượng và nhiều màu sắc hơn.<br> \r\n<br> \r\nQuần Boxer SWE được sử dụng vải Oxford, định lượng 170gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(63, 'sp63.webp', 'sp63_2.jpg', 'sp63_3.jpg', 'sp63_4.jpg', 'BLAZE JEANS', 554000, 792000, '| SWE® | BLAZE JEANS<br> \r\nCOLOR: YELLOW<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> \r\nLAZE JEANS - Được sử dụng chất liệu vải jeans cotton 100% 12 Oz và xử lý wash màu kèm phun PP giúp tạo ra được tone màu độc đáo. Điểm nhấn của quần nằm ở những chi tiết cách điệu chạy dọc xung quanh ống, cùng mắt cáo ấn tượng được đặt khắp bề mặt quần. Mang đến sự phá cách và tinh nghịch cho những ai yêu quyến rũ. Form dáng BAGGY tạo sự rộng rãi, thoải mái khi sử dụng.<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(64, 'sp64.webp', 'sp64_2.webp', 'sp64_3.jpg', 'sp64_4.webp', 'BAGGY CARGO SHORTS - WHITE', 343000, 528000, '| SWE® | BAGGY CARGO SHORTS<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> BAGGY CARGO SHORTS - Những chiếc quần BAGGY SHORTS đang trở thành xu hướng hiện nay bởi sự thoải mái và kiểu dáng trendy. Nắm bắt điều đó nhà SWE đã cho ra mắt BAGGY CARGO SHORTS với điểm nhấn ở phần túi hộp được đặt 2 bên ống quần, giúp bạn mang theo được nhiều vật dụng khi ra đường. Phần lưng và ống quần được may dây rút để bạn có thể điều chỉnh phù hợp với tỉ lệ cơ thể.<br>\r\n <br>\r\nQuần baggy shorts SWE được sử dụng vải KAKI COTTON 100%, định lượng 215gsm, thiết kế form baggy nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(65, 'sp65.webp', 'sp65_2.webp', 'sp65_3.jpg', 'sp65_4.jpg', 'BAGGY CARGO SHORTS - BLACK', 343000, 528000, '| SWE® | BAGGY CARGO SHORTS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br> BAGGY CARGO SHORTS - Những chiếc quần BAGGY SHORTS đang trở thành xu hướng hiện nay bởi sự thoải mái và kiểu dáng trendy. Nắm bắt điều đó nhà SWE đã cho ra mắt BAGGY CARGO SHORTS với điểm nhấn ở phần túi hộp được đặt 2 bên ống quần, giúp bạn mang theo được nhiều vật dụng khi ra đường. Phần lưng và ống quần được may dây rút để bạn có thể điều chỉnh phù hợp với tỉ lệ cơ thể.<br>\r\n <br>\r\nQuần baggy shorts SWE được sử dụng vải KAKI COTTON 100%, định lượng 215gsm, thiết kế form baggy nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(66, 'sp66.webp', 'sp66_2.webp', 'sp66_3.webp', 'sp66_4.webp', 'KA SHORTS - WHITE', 275000, 462000, '| SWE® | KA SHORTS<br> \r\nCOLOR: WHITE<br> \r\nMATERIAL: 100% POLYESTER<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nKA SHORTS - Một chiếc quần shorts mới không thể thiếu trong tủ đồ của bạn vào những ngày hè nắng nóng, được sử dụng chất liệu vải dù trượt nước, form dáng rộng rãi tạo sự thoải mái và thoáng mát khi sử dụng. Điếm nhấn nằm ở họa tiết KID ATELIER được thêu tệp với màu quần ở mặt trước sẽ giúp bạn dễ dàng phối đồ hơn.<br>\r\n <br>\r\nQuần shorts SWE vẫn được sử dụng POLYESTER 100%, định lượng 120gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(67, 'sp67.webp', 'sp67_2.webp', 'sp67_3.webp', 'sp67_4.jpg', 'KA SHORTS - RED', 275000, 462000, '| SWE® | KA SHORTS<br> \r\nCOLOR: RED<br> \r\nMATERIAL: 100% POLYESTER<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nKA SHORTS - Một chiếc quần shorts mới không thể thiếu trong tủ đồ của bạn vào những ngày hè nắng nóng, được sử dụng chất liệu vải dù trượt nước, form dáng rộng rãi tạo sự thoải mái và thoáng mát khi sử dụng. Điếm nhấn nằm ở họa tiết KID ATELIER được thêu tệp với màu quần ở mặt trước sẽ giúp bạn dễ dàng phối đồ hơn.<br>\r\n <br>\r\nQuần shorts SWE vẫn được sử dụng POLYESTER 100%, định lượng 120gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(68, 'sp68.webp', 'sp68_2.webp', 'sp68_3.webp', 'sp68_4.webp', 'KA SHORTS - BLACK', 275000, 462000, '| SWE® | KA SHORTS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: 100% POLYESTER<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nKA SHORTS - Một chiếc quần shorts mới không thể thiếu trong tủ đồ của bạn vào những ngày hè nắng nóng, được sử dụng chất liệu vải dù trượt nước, form dáng rộng rãi tạo sự thoải mái và thoáng mát khi sử dụng. Điếm nhấn nằm ở họa tiết KID ATELIER được thêu tệp với màu quần ở mặt trước sẽ giúp bạn dễ dàng phối đồ hơn.<br>\r\n <br>\r\nQuần shorts SWE vẫn được sử dụng POLYESTER 100%, định lượng 120gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(69, 'sp69.webp', 'sp69_2.webp', 'sp69_3.webp', 'sp69_4.webp', 'SPORT SHORTS - BLACK', 280000, 385000, '| SWE® | SPORT SHORTS<br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: 100% POLYESTER<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nSPORT SHORTS - Sử dụng chất vải dù trượt nước 100% polyester, form dáng rộng rãi tạo sự thoải mái và thoáng mát khi sử dụng, logo SWE được thêu dưới mép đùi trái tệp với màu quần sẽ giúp bạn dễ dàng phối đồ.<br>\r\n <br>\r\nQuần shorts SWE vẫn được sử dụng POLYESTER 100%, định lượng 120gsm nên chất lượng các bạn có thể hoàn toàn yên tâm với sản phẩm nhà SWE. <br> <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(70, 'sp70.webp', 'sp70_2.webp', 'sp70_3.webp', 'sp70_4.jpg', 'PLEATED PANTS - BLACK', 275000, 605000, '| SWE® | PLEATED PANTS <br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: 100% POLYESTER<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nPLEATED PANTS - Sử dụng chất vải có chất liệu 100% được dệt từ Polyester, định lượng 340gsm, form dáng suông, tạo sự rộng rãi, thoải mái và không kém phần lịch sự khi sử dụng.\r\n<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(71, 'sp71.jpg', 'sp71_2.jpg', 'sp71_3.jpg', 'sp71_4.webp', 'WASHED JEANS - BLACK', 455000, 759000, '| SWE® | WASHED JEANS - BLACK <br> \r\nCOLOR: BLACK<br> \r\nMATERIAL: DENIM<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\nWASHED JEANS sử dụng chất vải DENIM dày dặn (12.5 Oz đến 13.5 Oz) kèm light wash với màu nâu xám form BAGGY, tạo sự rộng rãi, thoải mái và không kém phần lịch sự khi sử dụng.\r\n<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5),
(72, 'sp72.webp', 'sp72_2.webp', 'sp72_3.jpg', 'sp72_4.webp', 'BUTTON CARGO PANTS - CREAM', 540000, 720000, '| SWE® | BUTTON CARGO PANTS <br> \r\nCOLOR: CREAM<br> \r\nMATERIAL: COTTON 100%<br> \r\nSIZE: S/M/L/XL<br> \r\n<br>\r\n| SWE® | BUTTON CARGO PANTS - Chiếc quần có form CARGO, được làm bằng chất liệu JEANS MỘC, dày dặn, thiết kế nhiều túi hộp cùng phần đính khuy bấm ở hai ống quần, có thể thay đổi form dáng tùy theo sở thích. \r\n<br>\r\n <br>\r\n\r\nForm quần được Fit size theo form và tiêu chuẩn tương đối của người Việt Nam, nếu bạn đang cân nhắc giữa hai size, nên chọn size lớn hơn.<br>\r\nSize S: Chiều cao dưới 1m65, cân nặng dưới 55kg<br>\r\nSize M: Chiều cao từ 1m65 - 1m75, cân nặng dưới 65kg<br>\r\nSize L: Chiều cao từ 1m75 - 1m85, cân nặng dưới 90kg<br>\r\nSize XL: Chiều cao từ 1m85 trở lên, cân nặng dưới 120kg<br> \r\n<br> \r\nCác bạn vui lòng tham khảo bảng size chart trước khi đặt hàng.<br>\r\n* Lưu ý: Hạn chế sử dụng máy sấy nhiệt cao để giữ form quần<br> \r\n<br> \r\nNOW AVAILABLE ONLINE & IN - STORE<br>\r\n', NULL, '2024-11-21', 'còn hàng', 5);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `reviews`
--

CREATE TABLE `reviews` (
  `id` int(100) NOT NULL,
  `review` varchar(500) DEFAULT NULL,
  `review_date` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `id` int(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `birthday` date DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `role` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`id`),
  ADD KEY `users_id` (`users_id`);

--
-- Chỉ mục cho bảng `orders_details`
--
ALTER TABLE `orders_details`
  ADD PRIMARY KEY (`id`),
  ADD KEY `product_id` (`product_id`),
  ADD KEY `order_id` (`order_id`);

--
-- Chỉ mục cho bảng `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `categories_id` (`categories_id`);

--
-- Chỉ mục cho bảng `reviews`
--
ALTER TABLE `reviews`
  ADD PRIMARY KEY (`id`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT cho bảng `orders`
--
ALTER TABLE `orders`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `orders_details`
--
ALTER TABLE `orders_details`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `products`
--
ALTER TABLE `products`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=73;

--
-- AUTO_INCREMENT cho bảng `reviews`
--
ALTER TABLE `reviews`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT cho bảng `users`
--
ALTER TABLE `users`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `orders`
--
ALTER TABLE `orders`
  ADD CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`);

--
-- Các ràng buộc cho bảng `orders_details`
--
ALTER TABLE `orders_details`
  ADD CONSTRAINT `orders_details_ibfk_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  ADD CONSTRAINT `orders_details_ibfk_2` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`);

--
-- Các ràng buộc cho bảng `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`categories_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Các ràng buộc cho bảng `reviews`
--
ALTER TABLE `reviews`
  ADD CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`id`) REFERENCES `orders` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
