const products = [
    {
        id: 1,
        sale: 23,
        image: "img/sp1.webp",
        image2: "img/sp1_2.webp",
        image3: "img/sp1_3.webp",
        image4: "img/sp1_4.webp",
        image5: "img/sp1_5.webp",
        image6: "img/sp1_6.webp",
        image7: "img/sp1_3.webp",
        name: "2BAR BABY TEE - BLUE",
        price: 221000,
        originalPrice: 286000,
        rating: 5,
        reviews: 1
    },
    {
        id: 2,
        sale: 23,
        image: "img/sp2.jpg",
        image2: "img/sp2_2.webp",
        image3: "img/sp2_3.webp",
        image4: "img/sp2_4.webp",
        image5: "img/sp2_5.webp",
        image6: "img/sp2_6.webp",
        image7: "img/sp2_3.webp",
        name: "2BAR BABY TEE - RED",
        price: 221000,
        originalPrice: 286000,
        rating: 5,
        reviews: 1
    },
    {
        id: 3,
        sale: 23,
        image: "img/sp3.jpg",
        image2: "img/sp3_2.webp",
        image3: "img/sp3_3.webp",
        image4: "img/sp3_4.webp",
        image5: "img/sp3_2.webp",
        image6: "img/sp3_3.webp",
        image7: "img/sp3_4.webp",
        name: "2BAR SHORTS - BLUE",
        price: 272000,
        originalPrice: 352000,
        rating: 5,
        reviews: 2
    },
    {
        id: 4,
        sale: 23,
        image: "img/sp4.webp",
        image2: "img/sp4_2.jpg",
        image3: "img/sp4_3.webp",
        image4: "img/sp4_4.webp",
        image5: "img/sp4_2.jpg",
        image6: "img/sp4_3.webp",
        image7: "img/sp4_4.webp",
        name: "2BAR SHORTS - RED",
        price: 272000,
        originalPrice: 352000,
        rating: 5,
        reviews: 1
    },
    {
        id: 5,
        sale: 35,
        image: "img/sp5.webp",
        image2: "img/sp5_2.jpg",
        image3: "img/sp5_3.jpg",
        image4: "img/sp5_4.webp",
        image5: "img/sp5_5.jpg",
        image6: "img/sp5_6.jpg",
        image7: "img/sp5_7.webp",
        name: "24 TEE - RED",
        price: 300000,
        originalPrice: 426000,
        rating: 0,
        reviews: 0
    },
    {
        id: 6,
        sale: 30,
        image: "img/sp6.webp",
        image2: "img/sp6_2.webp",
        image3: "img/sp6_3.webp",
        image4: "img/sp6_4.webp",
        image5: "img/sp6_5.webp",
        image6: "img/sp6_6.webp",
        image7: "img/sp6_7.webp",
        name: "EYE TEE - BLACK",
        price: 270000,
        originalPrice: 385000,
        rating: 0,
        reviews: 0
    },
    {
        id: 7,
        sale: 9,
        image: "img/sp7.webp",
        image2: "img/sp7_2.webp",
        image3: "img/sp7_3.webp",
        image4: "img/sp7_4.webp",
        image5: "img/sp7_5.webp",
        image6: "img/sp7_6.webp",
        image7: "img/sp7_7.jpg",
        name: "HAPPY TEE - BLACK",
        price: 330000,
        originalPrice: 363000,
        rating: 0,
        reviews: 0
    },
    {
        id: 8,
        sale: 27,
        image: "img/sp8.webp",
        image2: "img/sp8_2.webp",
        image3: "img/sp8_3.webp",
        image4: "img/sp8_4.webp",
        image5: "img/sp8_5.webp",
        image6: "img/sp8_6.webp",
        image7: "img/sp8_7.webp",
        name: "HEARTS TEE - BLACK",
        price: 280000,
        originalPrice: 385000,
        rating: 0,
        reviews: 0
    },
    {
        id: 9,
        sale: 39,
        image: "img/sp9.webp",
        image2: "img/sp9_2.webp",
        image3: "img/sp9_3.webp",
        image4: "img/sp9_4.webp",
        image5: "img/sp9_5.webp",
        image6: "img/sp9_6.webp",
        image7: "img/sp9_7.webp",
        name: "ILY TEE - CREAM",
        price: 280000,
        originalPrice: 462000,
        rating: 0,
        reviews: 0
    },
    {
        id: 10,
        sale: 9,
        image: "img/sp11.webp",
        image2: "img/sp10_2.webp",
        image3: "img/sp10_3.webp",
        image4: "img/sp10_4.webp",
        image5: "img/sp10_5.webp",
        image6: "img/sp10_6.webp",
        image7: "img/sp10_7.webp",
        name: "KID TEE - WHITE",
        price: 420000,
        originalPrice: 462000,
        rating: 0,
        reviews: 0
    },
    {
        id: 11,
        sale: 9,
        image: "img/sp10.webp",
        image2: "img/sp11_2.webp",
        image3: "img/sp11_3.webp",
        image4: "img/sp11_4.webp",
        image5: "img/sp11_5.webp",
        image6: "img/sp11_6.webp",
        image7: "img/sp11_7.webp",
        name: "SIGNATURE TEE - PINK",
        price: 380000,
        originalPrice: 418000,
        rating: 0,
        reviews: 0
    },
    {
        id: 12,
        sale: 9,
        image: "img/sp12.webp",
        image2: "img/sp12_2.webp",
        image3: "img/sp12_3.webp",
        image4: "img/sp12_4.webp",
        image5: "img/sp12_5.webp",
        image6: "img/sp12_6.webp",
        image7: "img/sp12_7.webp",
        name: "SWEVN TEE - BLACK",
        price: 350000,
        originalPrice: 385000,
        rating: 0,
        reviews: 0
    }
    // Thêm các sản phẩm khác vào đây
];
